// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://ajlytimpconhazplejln.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqbHl0aW1wY29uaGF6cGxlamxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzU0MjIsImV4cCI6MjA2MDc1MTQyMn0.6wqYeWE7u7NTGJ1itPxvyqb8xng_WvEGKKbPWsL9HSg';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);